### ISSUE TITLE
About auto-playing and "cloudmusic.music.unblock" in setting

### ISSUE THREAD

**Issue by MrAru** [YXL76/cloudmusic-vscode#435]
Since version 8.2.0, when I click on the icon in the activitybar, cloudmusic automatically loads and starts to play the recommended track of the day at the same time. This behavior sometimes causes some bad user experience (for example, I don't have my headphones plugged in at this time). I would like to know if this is a designed feature, or just a bug.

Also, the Readme file mentions the possibility to enable other music sources by setting `cloudmusic.music.unblock` in configuration, but I found there is no corresponding setting item. According to [the code here](https://github.com/YXL76/cloudmusic-vscode/blob/944dfba4b56be745867f4bcfb8490f78c8163055/src/constant/setting.ts#L12-L15), should I add these corresponding items in the JSON configuration file manually?

Version info:
VSCode 1.56.1
cloudmusic 8.2.2

**Comment by YXL76** [comment]
1. This is not a bug. Maybe I can disable autoplay.
2. The code you mentioned is from the previous version. According to [UnblockNeteaseMusic#743](https://github.com/nondanee/UnblockNeteaseMusic/issues/743), I think the benefits of maintaining this feature are too small. Therefore, it was removed since v8.0.0. Instead, I'm working on #343 .

**Comment by MrAru** [comment]
Thanks for your quick reply. I'll close this issue.
